# general content

title: jekyll example
email: alex@worldx3.com
description: Basic template for jekyll
baseurl: "/jekyll-example" # /jekyll-example
url: "https://gruncho.github.io/jekyll-example" # https://gruncho.github.io/jekyll-example

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# Sass settings

sass:
  sass_dir: assets/scss
  style: :compressed

# Gems

plugins:
  - jekyll-feed

authors:
  gruncho:
    name: gruncho
